- name: "Create expected folders"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0750'
    owner: 'root'
    group: '101'
  loop:
    - "{{ kea_container_base_dir }}"
    - "{{ kea_container_base_dir }}/config"
    - "{{ kea_container_base_dir }}/leases"
    - "{{ kea_container_base_dir }}/logs"
    - "{{ kea_container_base_dir }}/sockets"
    - "{{ kea_container_base_dir }}/entrypoint.d"

- name: Deploy the DHCP services
  ansible.builtin.include_tasks: deploy_dhcp.yml
  loop:
    - container_name: "{{ kea_dhcp4_container_name }}"
      container_image: "{{ kea_dhcp4_container_image }}"
      container_command: "{{ kea_dhcp4_container_command }}"
      dhcp_ip_version: "4"
      enabled: "{{ kea_dhcp4_enabled | bool }}"
    - container_name: "{{ kea_dhcp6_container_name }}"
      container_image: "{{ kea_dhcp6_container_image }}"
      container_command: "{{ kea_dhcp6_container_command }}"
      dhcp_ip_version: "6"
      enabled: "{{ kea_dhcp6_enabled | bool }}"
  loop_control:
    loop_var: "outer_item"
  when: outer_item.enabled
